-- Gold theme colors (gold on white / light)
return {
  name = "gold",
  colorscheme = "dawnfox", -- light nightfox variant, sits on the cream terminal bg
  plugin = "EdenEast/nightfox.nvim",

  -- Syntax highlights (nightfox groups) — everything in the gold family, readable on cream
  highlights = {
    NonText = "#C9B98A",
    Comment = "#B8A45C",
    String = "#A8841C",
    Number = "#C9952E",
    Float = "#C9952E",
    Boolean = "#C9952E",
    Identifier = "#8A6512",
    ["@variable"] = "#8A6512",
    ["@variable.member"] = "#9A7518",
    ["@property"] = "#9A7518",
    ["@field"] = "#9A7518",
    ["@variable.parameter"] = "#A87F1A",
    ["@parameter"] = "#A87F1A",
    Parameter = "#A87F1A",
    ["@function.call"] = "#BF9B30",
    ["@keyword.function"] = "#B58A1E",
    Function = "#BF9B30",
    ["@keyword.return"] = "#B58A1E",
    Conditional = "#B58A1E",
    Repeat = "#B58A1E",
    Operator = "#9A7518",
    Delimiter = "#7A5E12",
    ["@punctuation.bracket"] = "#7A5E12",
    ["@punctuation.delimiter"] = "#7A5E12",
    Constant = "#C9952E",
    ["@constant.builtin"] = "#C9952E",
    PreProc = "#A87F1A",
    ["@function.builtin"] = "#BF9B30",
    ["@module"] = "#9A7518",
    ["@constructor"] = "#A8841C",
    ["@variable.builtin"] = "#8A6512",
    ["@punctuation.special"] = "#D4AF37",
    Special = "#C9952E",
    ["@string.special"] = "#C9952E",
    ["@string.special.path"] = "#BF9B30",
    ["@string.special.path.bash"] = "#BF9B30",
    Type = "#9A7518",
    ["@type.builtin"] = "#9A7518",
    Keyword = "#B58A1E",
  },

  extra_highlights = {
    Normal = { fg = "#7A5E12", bg = "None" },
    Special = { fg = "#C9952E" },
    SnacksDashboardDesc = { fg = "#C9A227" },
    ["@string.special.path"] = { fg = "#BF9B30" },
    ["@string.special.path.bash"] = { fg = "#BF9B30" },
    Identifier = { fg = "#8A6512" },
    ["@variable"] = { fg = "#8A6512" },
    LspSignatureActiveParameter = { fg = "#C9A227", bold = true },
    Statement = { fg = "#B58A1E", italic = true },
    Conceal = { fg = "#B8A45C" },
    texNormal = { fg = "#7A5E12" },
    CursorLine = { bg = "#F0E4B0" },
    Visual = { bg = "#F0E4B0" },
    CursorLineNr = { fg = "#C9A227", bold = true },
    LineNr = { fg = "#C9B98A" },
  },

  -- Lualine colors (dark-gold bar against the cream editor)
  lualine = {
    bg_dark = "#4A3A10",
    bg_mid = "#5C4708",
    fg = "#F0E4B0",
    fg_bright = "#FAF7F0",
    accent = "#D4AF37",
    accent_alt = "#BF9B30",
    warning = "#C9952E",
  },
}
